/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`action_logs_get_entity_action_log`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionLogsGetEntityActionLogError {
    Status404(models::ActionLogsGetEntityActionLog404Response),
    Status400(models::ActionLogsGetEntityActionLog400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`action_logs_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionLogsUpdateError {
    Status404(models::ActionLogsUpdate404Response),
    UnknownValue(serde_json::Value),
}


/// Retrieve action logs for a given entity type (users, organisations) by ID.
pub async fn action_logs_get_entity_action_log(configuration: &configuration::Configuration, entity: &str, id: i32) -> Result<models::ActionLogsGetEntityActionLog200Response, Error<ActionLogsGetEntityActionLogError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_entity = entity;
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/{entity}/{id}/action_log", configuration.base_path, entity=crate::apis::urlencode(p_path_entity), id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ActionLogsGetEntityActionLog200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ActionLogsGetEntityActionLog200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ActionLogsGetEntityActionLogError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update an action log entry, including marking it as complete or incomplete.
pub async fn action_logs_update(configuration: &configuration::Configuration, id: i32, complete: Option<bool>, incomplete: Option<bool>) -> Result<models::ActionLogsUpdate200Response, Error<ActionLogsUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_complete = complete;
    let p_query_incomplete = incomplete;

    let uri_str = format!("{}/api/v1/action_logs/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref param_value) = p_query_complete {
        req_builder = req_builder.query(&[("complete", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_incomplete {
        req_builder = req_builder.query(&[("incomplete", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ActionLogsUpdate200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ActionLogsUpdate200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ActionLogsUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

