/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`custodians_create_custodian_validation_checks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansCreateCustodianValidationChecksError {
    Status400(models::CustodiansCreateCustodianValidationChecks400Response),
    Status404(models::CustodiansGetRules404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodians_get_custodian_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansGetCustodianUsersError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodiansGetCustodianUsers404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodians_get_custodian_validation_checks`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansGetCustodianValidationChecksError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodiansGetRules404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodians_get_organisation_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansGetOrganisationUsersError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodiansGetOrganisationUsers404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodians_get_rules`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansGetRulesError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodiansGetRules404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodians_get_statuses_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodiansGetStatusesUsersError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodiansGetOrganisationUsers404Response),
    UnknownValue(serde_json::Value),
}


/// Creates a new validation check and assigns it to a specific custodian via the custodian_has_validation_check pivot table.
pub async fn custodians_create_custodian_validation_checks(configuration: &configuration::Configuration, custodian_id: i32, custodians_create_custodian_validation_checks_request: models::CustodiansCreateCustodianValidationChecksRequest) -> Result<models::ValidationCheck, Error<CustodiansCreateCustodianValidationChecksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_body_custodians_create_custodian_validation_checks_request = custodians_create_custodian_validation_checks_request;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/validation_checks", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_custodians_create_custodian_validation_checks_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ValidationCheck`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ValidationCheck`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansCreateCustodianValidationChecksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches the list of custodian users based on the custodian id.
pub async fn custodians_get_custodian_users(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::CustodiansGetCustodianUsers200Response, Error<CustodiansGetCustodianUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/custodian_users", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodiansGetCustodianUsers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodiansGetCustodianUsers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansGetCustodianUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the list of validation checks associated with a specific custodian.
pub async fn custodians_get_custodian_validation_checks(configuration: &configuration::Configuration, custodian_id: i32) -> Result<Vec<models::ValidationCheck>, Error<CustodiansGetCustodianValidationChecksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/validation_checks", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::ValidationCheck&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::ValidationCheck&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansGetCustodianValidationChecksError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches the list of users associated with the given custodian and organisations IDs.
pub async fn custodians_get_organisation_users(configuration: &configuration::Configuration, custodian_id: i32, organisation_id: i32) -> Result<models::CustodiansGetOrganisationUsers200Response, Error<CustodiansGetOrganisationUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_organisation_id = organisation_id;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/organisations/{organisationId}/users", configuration.base_path, custodianId=p_path_custodian_id, organisationId=p_path_organisation_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodiansGetOrganisationUsers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodiansGetOrganisationUsers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansGetOrganisationUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches the list of rules associated with the given custodian ID.
pub async fn custodians_get_rules(configuration: &configuration::Configuration, id: i32) -> Result<models::CustodiansGetRules200Response, Error<CustodiansGetRulesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/custodians/{id}/rules", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodiansGetRules200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodiansGetRules200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansGetRulesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetches the user statuses given custodian and organisations and project and user IDs.
pub async fn custodians_get_statuses_users(configuration: &configuration::Configuration, custodian_id: i32, project_user_id: i32) -> Result<models::CustodiansGetOrganisationUsers200Response, Error<CustodiansGetStatusesUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_project_user_id = project_user_id;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/projectUsers/{projectUserId}/statuses", configuration.base_path, custodianId=p_path_custodian_id, projectUserId=p_path_project_user_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodiansGetOrganisationUsers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodiansGetOrganisationUsers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodiansGetStatusesUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

