/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`custodian_project_organisations_get_workflow_states`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianProjectOrganisationsGetWorkflowStatesError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_project_organisations_index`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianProjectOrganisationsIndexError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status403(models::CustodianProjectOrganisationsIndex403Response),
    Status404(models::CustodiansGetRules404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_project_organisations_show`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianProjectOrganisationsShowError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status403(models::CustodianProjectOrganisationsIndex403Response),
    Status404(models::CustodianProjectOrganisationsShow404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_project_organisations_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianProjectOrganisationsUpdateError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status403(models::CustodianProjectOrganisationsIndex403Response),
    Status404(models::CustodianProjectOrganisationsShow404Response),
    Status500(models::CustodianProjectOrganisationsUpdate500Response),
    UnknownValue(serde_json::Value),
}


/// Returns a list of all possible workflow states
pub async fn custodian_project_organisations_get_workflow_states(configuration: &configuration::Configuration, ) -> Result<models::CustodianProjectOrganisationsGetWorkflowStates200Response, Error<CustodianProjectOrganisationsGetWorkflowStatesError>> {

    let uri_str = format!("{}/api/v1/custodian_approvals/projectOrganisations/getWorkflowStates", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetWorkflowStates200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetWorkflowStates200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianProjectOrganisationsGetWorkflowStatesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns a list of all custodian project organisation approvals for a specific custodian
pub async fn custodian_project_organisations_index(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::CustodianProjectOrganisationsIndex200Response, Error<CustodianProjectOrganisationsIndexError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodian_approvals/{custodianId}/projectOrganisations", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsIndex200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsIndex200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianProjectOrganisationsIndexError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns custodian approval details for a specific project organisation
pub async fn custodian_project_organisations_show(configuration: &configuration::Configuration, custodian_id: i32, project_organisation_id: i32) -> Result<models::CustodianProjectOrganisationsShow200Response, Error<CustodianProjectOrganisationsShowError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_project_organisation_id = project_organisation_id;

    let uri_str = format!("{}/api/v1/custodian_approvals/{custodianId}/projectOrganisations/{projectOrganisationId}", configuration.base_path, custodianId=p_path_custodian_id, projectOrganisationId=p_path_project_organisation_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsShow200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsShow200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianProjectOrganisationsShowError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates approval status and/or comment for a project organisation
pub async fn custodian_project_organisations_update(configuration: &configuration::Configuration, custodian_id: i32, project_organisation_id: i32, custodian_project_organisations_update_request: models::CustodianProjectOrganisationsUpdateRequest) -> Result<models::CustodianProjectOrganisationsShow200Response, Error<CustodianProjectOrganisationsUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_project_organisation_id = project_organisation_id;
    let p_body_custodian_project_organisations_update_request = custodian_project_organisations_update_request;

    let uri_str = format!("{}/api/v1/custodian_approvals/{custodianId}/projectOrganisations/{projectOrganisationId}", configuration.base_path, custodianId=p_path_custodian_id, projectOrganisationId=p_path_project_organisation_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_custodian_project_organisations_update_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsShow200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsShow200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianProjectOrganisationsUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

