/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`custodian_add_project`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianAddProjectError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_destroy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianDestroyError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_get_organisations`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianGetOrganisationsError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_get_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianGetProjectsError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_get_projects_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianGetProjectsUsersError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_get_user_projects`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianGetUserProjectsError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodianGetUserProjects404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_index`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianIndexError {
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_show`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianShowError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_show_by_unique_identifier`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianShowByUniqueIdentifierError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_store`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianStoreError {
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`custodian_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianUpdateError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}


/// Create a project for a custodian
pub async fn custodian_add_project(configuration: &configuration::Configuration, custodian_id: i32, custodian_add_project_request: models::CustodianAddProjectRequest) -> Result<models::CustodianAddProject201Response, Error<CustodianAddProjectError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_body_custodian_add_project_request = custodian_add_project_request;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/projects", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_custodian_add_project_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianAddProject201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianAddProject201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianAddProjectError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete a Custodian entry from the system
pub async fn custodian_destroy(configuration: &configuration::Configuration, id: i32) -> Result<models::AffiliationDestroy200Response, Error<CustodianDestroyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/custodians/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AffiliationDestroy200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AffiliationDestroy200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianDestroyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch a list of custodians organisations with projects, along with pagination details.
pub async fn custodian_get_organisations(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::CustodianGetOrganisations200Response, Error<CustodianGetOrganisationsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodian/{custodianId}/organisations", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianGetOrganisations200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianGetOrganisations200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianGetOrganisationsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch a list of projects along with pagination details for a specified custodian.
pub async fn custodian_get_projects(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::CustodianGetProjects200Response, Error<CustodianGetProjectsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodian/{custodianId}/projects", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianGetProjects200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianGetProjects200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianGetProjectsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns paginated users for all projects under a specific custodian.
pub async fn custodian_get_projects_users(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::CustodianGetProjectsUsers200Response, Error<CustodianGetProjectsUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/custodians/{custodianId}/projects_users", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianGetProjectsUsers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianGetProjectsUsers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianGetProjectsUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Fetch a list of custodians projects associated with a user, along with pagination details.
pub async fn custodian_get_user_projects(configuration: &configuration::Configuration, custodian_id: i32, user_id: i32) -> Result<models::CustodianGetUserProjects200Response, Error<CustodianGetUserProjectsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_user_id = user_id;

    let uri_str = format!("{}/api/v1/custodian/{custodianId}/users/{userId}/projects", configuration.base_path, custodianId=p_path_custodian_id, userId=p_path_user_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianGetUserProjects200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianGetUserProjects200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianGetUserProjectsError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return a list of Custodians
pub async fn custodian_index(configuration: &configuration::Configuration, ) -> Result<models::CustodianIndex200Response, Error<CustodianIndexError>> {

    let uri_str = format!("{}/api/v1/custodians", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianIndex200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianIndex200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianIndexError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return an Custodian entry by ID
pub async fn custodian_show(configuration: &configuration::Configuration, id: i32) -> Result<models::CustodianIndex200Response, Error<CustodianShowError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/custodians/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianIndex200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianIndex200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianShowError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return an Custodian entry by Unique Identifier
pub async fn custodian_show_by_unique_identifier(configuration: &configuration::Configuration, id: &str) -> Result<models::CustodianIndex200Response, Error<CustodianShowByUniqueIdentifierError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/custodians/identifier/{id}", configuration.base_path, id=crate::apis::urlencode(p_path_id));
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianIndex200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianIndex200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianShowByUniqueIdentifierError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a Custodian entry
pub async fn custodian_store(configuration: &configuration::Configuration, custodian_store_request: models::CustodianStoreRequest) -> Result<models::CustodianStore201Response, Error<CustodianStoreError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_custodian_store_request = custodian_store_request;

    let uri_str = format!("{}/api/v1/custodians", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_custodian_store_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianStore201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianStore201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianStoreError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Edit a Custodian entry
pub async fn custodian_update(configuration: &configuration::Configuration, id: i32, custodian_store_request: models::CustodianStoreRequest) -> Result<models::CustodianStore201Response, Error<CustodianUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_custodian_store_request = custodian_store_request;

    let uri_str = format!("{}/api/v1/custodians/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_custodian_store_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianStore201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianStore201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

