/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`custodian_project_organisations_get_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustodianProjectOrganisationsGetStatusError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::CustodianProjectOrganisationsGetStatus404Response),
    Status500(models::CustodianProjectOrganisationsGetStatus500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_custodian_invite_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsCustodianInviteUserError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_destroy`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsDestroyError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_get_registries`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsGetRegistriesError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::OrganisationsGetRegistries404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_get_status`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsGetStatusError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::OrganisationsGetStatus404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_idvt`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsIdvtError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_invite_user`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsInviteUserError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status403(models::OrganisationsInviteUser403Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_show`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsShowError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_store`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsStoreError {
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsUpdateError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`organisations_update_approved`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum OrganisationsUpdateApprovedError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}


/// Retrieve the status of a project organisation for a specific custodian using custodianId, projectId, and organisationId.
pub async fn custodian_project_organisations_get_status(configuration: &configuration::Configuration, custodian_id: i32, project_id: i32, organisation_id: i32) -> Result<models::CustodianProjectOrganisationsGetStatus200Response, Error<CustodianProjectOrganisationsGetStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_path_project_id = project_id;
    let p_path_organisation_id = organisation_id;

    let uri_str = format!("{}/api/v1/custodian_approvals/{custodianId}/project/{projectId}/organisation/{organisationId}/projectOrganisations/status", configuration.base_path, custodianId=p_path_custodian_id, projectId=p_path_project_id, organisationId=p_path_organisation_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetStatus200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetStatus200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<CustodianProjectOrganisationsGetStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Invites a user to org
pub async fn organisations_custodian_invite_user(configuration: &configuration::Configuration, id: i32, organisations_invite_user_request: models::OrganisationsInviteUserRequest) -> Result<models::AccreditationStoreByRegistryId201Response, Error<OrganisationsCustodianInviteUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_organisations_invite_user_request = organisations_invite_user_request;

    let uri_str = format!("{}/api/v1/organisations/{id}/custodian_invite_user", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_organisations_invite_user_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsCustodianInviteUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Delete an organisations entry from the system
pub async fn organisations_destroy(configuration: &configuration::Configuration, id: i32) -> Result<models::AffiliationDestroy200Response, Error<OrganisationsDestroyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/organisations/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AffiliationDestroy200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AffiliationDestroy200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsDestroyError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns all registries associated with the specified organisation
pub async fn organisations_get_registries(configuration: &configuration::Configuration, id: i64, show_pending: Option<bool>) -> Result<models::OrganisationsGetRegistries200Response, Error<OrganisationsGetRegistriesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_query_show_pending = show_pending;

    let uri_str = format!("{}/api/v1/organisations/{id}/registries", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_show_pending {
        req_builder = req_builder.query(&[("show_pending", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganisationsGetRegistries200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganisationsGetRegistries200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsGetRegistriesError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns the organisation with its model state and state
pub async fn organisations_get_status(configuration: &configuration::Configuration, id: i32) -> Result<models::CustodianProjectOrganisationsGetStatus200Response, Error<OrganisationsGetStatusError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/organisations/{id}/status", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetStatus200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::CustodianProjectOrganisationsGetStatus200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsGetStatusError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return an organisations idvt details by ID
pub async fn organisations_idvt(configuration: &configuration::Configuration, id: i32) -> Result<models::OrganisationsIdvt200Response, Error<OrganisationsIdvtError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/organisations/{id}/idvt", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganisationsIdvt200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganisationsIdvt200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsIdvtError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Invites a user to org
pub async fn organisations_invite_user(configuration: &configuration::Configuration, id: i32, organisations_invite_user_request: models::OrganisationsInviteUserRequest) -> Result<models::AccreditationStoreByRegistryId201Response, Error<OrganisationsInviteUserError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_organisations_invite_user_request = organisations_invite_user_request;

    let uri_str = format!("{}/api/v1/organisations/{id}/invite_user", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_organisations_invite_user_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsInviteUserError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Return an organisations entry by ID
pub async fn organisations_show(configuration: &configuration::Configuration, id: i32) -> Result<models::OrganisationIndex200Response, Error<OrganisationsShowError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;

    let uri_str = format!("{}/api/v1/organisations/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganisationIndex200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganisationIndex200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsShowError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Create a organisations entry
pub async fn organisations_store(configuration: &configuration::Configuration, organisation: models::Organisation) -> Result<models::IdentityStore201Response, Error<OrganisationsStoreError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_organisation = organisation;

    let uri_str = format!("{}/api/v1/organisations", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_organisation);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::IdentityStore201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::IdentityStore201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsStoreError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Update a organisations entry
pub async fn organisations_update(configuration: &configuration::Configuration, id: i32, organisation: models::Organisation) -> Result<models::OrganisationsUpdate200Response, Error<OrganisationsUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_organisation = organisation;

    let uri_str = format!("{}/api/v1/organisations/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_organisation);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::OrganisationsUpdate200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::OrganisationsUpdate200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates the system_approved flag for an organisation
pub async fn organisations_update_approved(configuration: &configuration::Configuration, id: i32, organisations_update_approved_request: models::OrganisationsUpdateApprovedRequest) -> Result<models::AccreditationStoreByRegistryId201Response, Error<OrganisationsUpdateApprovedError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_organisations_update_approved_request = organisations_update_approved_request;

    let uri_str = format!("{}/api/v1/organisations/{id}/approved", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_organisations_update_approved_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<OrganisationsUpdateApprovedError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

