/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`professional_registrations_update`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProfessionalRegistrationsUpdateError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(models::AffiliationsIndexByRegistryId404Response),
    Status500(models::AffiliationsStoreByRegistryId500Response),
    UnknownValue(serde_json::Value),
}


/// Update a Professional Registrations entry
pub async fn professional_registrations_update(configuration: &configuration::Configuration, id: i32, professional_registrations_update_request: models::ProfessionalRegistrationsUpdateRequest) -> Result<models::ProfessionalRegistrationsUpdate200Response, Error<ProfessionalRegistrationsUpdateError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_id = id;
    let p_body_professional_registrations_update_request = professional_registrations_update_request;

    let uri_str = format!("{}/api/v1/professional_registrations/{id}", configuration.base_path, id=p_path_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_professional_registrations_update_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::ProfessionalRegistrationsUpdate200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::ProfessionalRegistrationsUpdate200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ProfessionalRegistrationsUpdateError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

