/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`project_users_bulk_invite_project_users`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ProjectUsersBulkInviteProjectUsersError {
    UnknownValue(serde_json::Value),
}


/// Invite multiple users and attach them to a project
pub async fn project_users_bulk_invite_project_users(configuration: &configuration::Configuration, project_users_bulk_invite_project_users_request: models::ProjectUsersBulkInviteProjectUsersRequest) -> Result<(), Error<ProjectUsersBulkInviteProjectUsersError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_project_users_bulk_invite_project_users_request = project_users_bulk_invite_project_users_request;

    let uri_str = format!("{}/api/v1/project_users/bulk", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_project_users_bulk_invite_project_users_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<ProjectUsersBulkInviteProjectUsersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

