/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`resolution_index_by_registry_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResolutionIndexByRegistryIdError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`resolution_store_by_registry_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResolutionStoreByRegistryIdError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    UnknownValue(serde_json::Value),
}


pub async fn resolution_index_by_registry_id(configuration: &configuration::Configuration, registry_id: i32) -> Result<Vec<models::Resolution>, Error<ResolutionIndexByRegistryIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_registry_id = registry_id;

    let uri_str = format!("{}/api/v1/registries/{registryId}/resolutions", configuration.base_path, registryId=p_path_registry_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Resolution&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::Resolution&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ResolutionIndexByRegistryIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

pub async fn resolution_store_by_registry_id(configuration: &configuration::Configuration, registry_id: i32, resolution: models::Resolution) -> Result<models::AccreditationStoreByRegistryId201Response, Error<ResolutionStoreByRegistryIdError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_registry_id = registry_id;
    let p_body_resolution = resolution;

    let uri_str = format!("{}/api/v1/registries/{registryId}/resolutions", configuration.base_path, registryId=p_path_registry_id);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_resolution);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccreditationStoreByRegistryId201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<ResolutionStoreByRegistryIdError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

