/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`webhooks_create_receiver`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksCreateReceiverError {
    Status422(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_delete_receiver`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksDeleteReceiverError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_get_all_event_triggers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksGetAllEventTriggersError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_get_all_receivers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksGetAllReceiversError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_get_receivers_by_custodian`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksGetReceiversByCustodianError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_sendgrid`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksSendgridError {
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`webhooks_update_receiver`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum WebhooksUpdateReceiverError {
    Status400(models::AccreditationIndexByRegistryId400Response),
    Status404(),
    Status422(),
    UnknownValue(serde_json::Value),
}


/// Creates a new webhook receiver for a custodian
pub async fn webhooks_create_receiver(configuration: &configuration::Configuration, webhooks_create_receiver_request: models::WebhooksCreateReceiverRequest) -> Result<models::WebhooksCreateReceiver201Response, Error<WebhooksCreateReceiverError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_body_webhooks_create_receiver_request = webhooks_create_receiver_request;

    let uri_str = format!("{}/api/v1/webhooks/receivers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_webhooks_create_receiver_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhooksCreateReceiver201Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhooksCreateReceiver201Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksCreateReceiverError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Deletes a specific webhook receiver for a custodian
pub async fn webhooks_delete_receiver(configuration: &configuration::Configuration, custodian_id: i32, webhooks_delete_receiver_request: models::WebhooksDeleteReceiverRequest) -> Result<models::EducationDestroyByRegistryId200Response, Error<WebhooksDeleteReceiverError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_body_webhooks_delete_receiver_request = webhooks_delete_receiver_request;

    let uri_str = format!("{}/api/v1/webhooks/receivers/{custodianId}", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_webhooks_delete_receiver_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EducationDestroyByRegistryId200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EducationDestroyByRegistryId200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksDeleteReceiverError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns all webhook event triggers
pub async fn webhooks_get_all_event_triggers(configuration: &configuration::Configuration, ) -> Result<models::WebhooksGetAllEventTriggers200Response, Error<WebhooksGetAllEventTriggersError>> {

    let uri_str = format!("{}/api/v1/webhooks/event-triggers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhooksGetAllEventTriggers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhooksGetAllEventTriggers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksGetAllEventTriggersError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns all webhook receivers with their associated event trigger details
pub async fn webhooks_get_all_receivers(configuration: &configuration::Configuration, ) -> Result<models::WebhooksGetAllReceivers200Response, Error<WebhooksGetAllReceiversError>> {

    let uri_str = format!("{}/api/v1/webhooks/receivers", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhooksGetAllReceivers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhooksGetAllReceivers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksGetAllReceiversError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns all webhook receivers for a specific custodian with their associated event trigger details
pub async fn webhooks_get_receivers_by_custodian(configuration: &configuration::Configuration, custodian_id: i32) -> Result<models::WebhooksGetAllReceivers200Response, Error<WebhooksGetReceiversByCustodianError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;

    let uri_str = format!("{}/api/v1/webhooks/receivers/{custodianId}", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::WebhooksGetAllReceivers200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::WebhooksGetAllReceivers200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksGetReceiversByCustodianError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Returns sendgrid webhook event triggers
pub async fn webhooks_sendgrid(configuration: &configuration::Configuration, ) -> Result<(), Error<WebhooksSendgridError>> {

    let uri_str = format!("{}/api/v1/webhooks/sendgrid", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksSendgridError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Updates a specific webhook receiver for a custodian
pub async fn webhooks_update_receiver(configuration: &configuration::Configuration, custodian_id: i32, webhooks_update_receiver_request: models::WebhooksUpdateReceiverRequest) -> Result<models::EducationDestroyByRegistryId200Response, Error<WebhooksUpdateReceiverError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_custodian_id = custodian_id;
    let p_body_webhooks_update_receiver_request = webhooks_update_receiver_request;

    let uri_str = format!("{}/api/v1/webhooks/receivers/{custodianId}", configuration.base_path, custodianId=p_path_custodian_id);
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_webhooks_update_receiver_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::EducationDestroyByRegistryId200Response`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::EducationDestroyByRegistryId200Response`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<WebhooksUpdateReceiverError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

