/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Accreditation : Accreditation model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Accreditation {
    /// Unique identifier for the accreditation
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the associated organisation
    #[serde(rename = "associated_organisation_name", skip_serializing_if = "Option::is_none")]
    pub associated_organisation_name: Option<String>,
    /// ID string for the accreditation
    #[serde(rename = "id_string", skip_serializing_if = "Option::is_none")]
    pub id_string: Option<String>,
    /// Date when the accreditation was issued
    #[serde(rename = "issue_date", skip_serializing_if = "Option::is_none")]
    pub issue_date: Option<chrono::NaiveDate>,
    /// Date when the accreditation expires
    #[serde(rename = "expiry_date", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<chrono::NaiveDate>,
    /// Timestamp when the accreditation was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the accreditation was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Accreditation {
    /// Accreditation model
    pub fn new() -> Accreditation {
        Accreditation {
            id: None,
            associated_organisation_name: None,
            id_string: None,
            issue_date: None,
            expiry_date: None,
            created_at: None,
            updated_at: None,
        }
    }
}

