/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionLog : Action Log model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionLog {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Type of the entity associated with the action log
    #[serde(rename = "entity_type", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    /// ID of the entity associated with the action log
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<i32>,
    /// Description of the action performed
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    /// Timestamp when the action was completed (nullable)
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ActionLog {
    /// Action Log model
    pub fn new() -> ActionLog {
        ActionLog {
            id: None,
            entity_type: None,
            entity_id: None,
            action: None,
            completed_at: None,
        }
    }
}

