/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Affiliation : Affiliation model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Affiliation {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    /// Organisational link
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
    /// Member ID UUID
    #[serde(rename = "member_id", skip_serializing_if = "Option::is_none")]
    pub member_id: Option<String>,
    /// Textual representation of affiliation relationship
    #[serde(rename = "relationship", skip_serializing_if = "Option::is_none")]
    pub relationship: Option<String>,
    /// Date affiliation commenced
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// Date affiliation concluded
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    /// Department worked during affiliation
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    /// Role held during affiliation
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    /// Professional email held during affiliation
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// The ROR.org identifier for this affiliation institute
    #[serde(rename = "ror", skip_serializing_if = "Option::is_none")]
    pub ror: Option<String>,
    /// The Registry primary key associated with this affiliation
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// Flag indicating if affiliation is for the current employer
    #[serde(rename = "current_employer", skip_serializing_if = "Option::is_none")]
    pub current_employer: Option<bool>,
    /// Unique verification code issued for confirmation
    #[serde(rename = "verification_code", skip_serializing_if = "Option::is_none")]
    pub verification_code: Option<String>,
    /// Timestamp when verification code was sent
    #[serde(rename = "verification_sent_at", skip_serializing_if = "Option::is_none")]
    pub verification_sent_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when verification was confirmed
    #[serde(rename = "verification_confirmed_at", skip_serializing_if = "Option::is_none")]
    pub verification_confirmed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Flag indicating if affiliation is verified
    #[serde(rename = "is_verified", skip_serializing_if = "Option::is_none")]
    pub is_verified: Option<bool>,
}

impl Affiliation {
    /// Affiliation model
    pub fn new() -> Affiliation {
        Affiliation {
            id: None,
            created_at: None,
            updated_at: None,
            organisation_id: None,
            member_id: None,
            relationship: None,
            from: None,
            to: None,
            department: None,
            role: None,
            email: None,
            ror: None,
            registry_id: None,
            current_employer: None,
            verification_code: None,
            verification_sent_at: None,
            verification_confirmed_at: None,
            is_verified: None,
        }
    }
}

