/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "organisation_name", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<String>,
    #[serde(rename = "unclaimed", skip_serializing_if = "Option::is_none")]
    pub unclaimed: Option<bool>,
    #[serde(rename = "lead_applicant_email", skip_serializing_if = "Option::is_none")]
    pub lead_applicant_email: Option<String>,
}

impl AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
    pub fn new() -> AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
        AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation {
            id: None,
            organisation_name: None,
            unclaimed: None,
            lead_applicant_email: None,
        }
    }
}

