/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AffiliationsGetOrganisationAffiliation200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
    #[serde(rename = "model_state_id", skip_serializing_if = "Option::is_none")]
    pub model_state_id: Option<i32>,
    #[serde(rename = "model_state", skip_serializing_if = "Option::is_none")]
    pub model_state: Option<Box<models::AffiliationsGetOrganisationAffiliation200ResponseDataModelState>>,
    #[serde(rename = "organisation", skip_serializing_if = "Option::is_none")]
    pub organisation: Option<Box<models::AffiliationsGetOrganisationAffiliation200ResponseDataOrganisation>>,
}

impl AffiliationsGetOrganisationAffiliation200ResponseData {
    pub fn new() -> AffiliationsGetOrganisationAffiliation200ResponseData {
        AffiliationsGetOrganisationAffiliation200ResponseData {
            id: None,
            registry_id: None,
            organisation_id: None,
            model_state_id: None,
            model_state: None,
            organisation: None,
        }
    }
}

