/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Charity : Charity model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Charity {
    /// Unique identifier for the charity
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Registration ID of the charity
    #[serde(rename = "registration_id", skip_serializing_if = "Option::is_none")]
    pub registration_id: Option<String>,
    /// Name of the charity
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Website URL of the charity
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// First line of the charity's address
    #[serde(rename = "address_1", skip_serializing_if = "Option::is_none")]
    pub address_1: Option<String>,
    /// Second line of the charity's address
    #[serde(rename = "address_2", skip_serializing_if = "Option::is_none")]
    pub address_2: Option<String>,
    /// Town where the charity is located
    #[serde(rename = "town", skip_serializing_if = "Option::is_none")]
    pub town: Option<String>,
    /// County where the charity is located
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    /// Country where the charity is located
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Postcode of the charity's address
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
}

impl Charity {
    /// Charity model
    pub fn new() -> Charity {
        Charity {
            id: None,
            registration_id: None,
            name: None,
            website: None,
            address_1: None,
            address_2: None,
            town: None,
            county: None,
            country: None,
            postcode: None,
        }
    }
}

