/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianUserShow200ResponseUserPermissionsInner {
    #[serde(rename = "custodian_user_id", skip_serializing_if = "Option::is_none")]
    pub custodian_user_id: Option<i32>,
    #[serde(rename = "permission_id", skip_serializing_if = "Option::is_none")]
    pub permission_id: Option<i32>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Box<models::Permission>>,
}

impl CustodianUserShow200ResponseUserPermissionsInner {
    pub fn new() -> CustodianUserShow200ResponseUserPermissionsInner {
        CustodianUserShow200ResponseUserPermissionsInner {
            custodian_user_id: None,
            permission_id: None,
            permission: None,
        }
    }
}

