/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "digi_ident", skip_serializing_if = "Option::is_none")]
    pub digi_ident: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerRegistryUser>>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {
        CustodianGetProjectsUsers200ResponseDataDataInnerRegistry {
            id: None,
            digi_ident: None,
            verified: None,
            user: None,
        }
    }
}

