/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInner {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "user_digital_ident", skip_serializing_if = "Option::is_none")]
    pub user_digital_ident: Option<String>,
    #[serde(rename = "project_role_id", skip_serializing_if = "Option::is_none")]
    pub project_role_id: Option<i32>,
    #[serde(rename = "primary_contact", skip_serializing_if = "Option::is_none")]
    pub primary_contact: Option<bool>,
    #[serde(rename = "affiliation_id", skip_serializing_if = "Option::is_none")]
    pub affiliation_id: Option<i32>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerRole>>,
    #[serde(rename = "affiliation", skip_serializing_if = "Option::is_none")]
    pub affiliation: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerAffiliation>>,
    #[serde(rename = "registry", skip_serializing_if = "Option::is_none")]
    pub registry: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerRegistry>>,
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerProject>>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInner {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInner {
        CustodianGetProjectsUsers200ResponseDataDataInner {
            project_id: None,
            user_digital_ident: None,
            project_role_id: None,
            primary_contact: None,
            affiliation_id: None,
            role: None,
            affiliation: None,
            registry: None,
            project: None,
        }
    }
}

