/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustodianHasProjectOrganisation : Custodian approval status for a project organisation
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianHasProjectOrganisation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the project organisation
    #[serde(rename = "project_has_organisation_id")]
    pub project_has_organisation_id: i32,
    /// ID of the custodian
    #[serde(rename = "custodian_id")]
    pub custodian_id: i32,
    /// Approval flag
    #[serde(rename = "approved", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approved: Option<Option<bool>>,
    /// Optional comment
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<String>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "projectOrganisation", skip_serializing_if = "Option::is_none")]
    pub project_organisation: Option<Box<models::ProjectHasOrganisation>>,
    #[serde(rename = "custodian", skip_serializing_if = "Option::is_none")]
    pub custodian: Option<Box<models::Custodian>>,
}

impl CustodianHasProjectOrganisation {
    /// Custodian approval status for a project organisation
    pub fn new(project_has_organisation_id: i32, custodian_id: i32) -> CustodianHasProjectOrganisation {
        CustodianHasProjectOrganisation {
            id: None,
            project_has_organisation_id,
            custodian_id,
            approved: None,
            comment: None,
            created_at: None,
            updated_at: None,
            project_organisation: None,
            custodian: None,
        }
    }
}

