/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInnerAffiliationOrganisation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "organisation_name", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<String>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInnerAffiliationOrganisation {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInnerAffiliationOrganisation {
        CustodianGetProjectsUsers200ResponseDataDataInnerAffiliationOrganisation {
            id: None,
            organisation_name: None,
        }
    }
}

