/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInnerProject {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInnerProject {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInnerProject {
        CustodianGetProjectsUsers200ResponseDataDataInnerProject {
            id: None,
            title: None,
        }
    }
}

