/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodiansCreateCustodianValidationChecksRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl CustodiansCreateCustodianValidationChecksRequest {
    pub fn new(name: String, r#type: String) -> CustodiansCreateCustodianValidationChecksRequest {
        CustodiansCreateCustodianValidationChecksRequest {
            name,
            r#type,
            description: None,
        }
    }
}

