/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustodianModelConfig : CustodianModelConfig model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianModelConfig {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "entity_model_id", skip_serializing_if = "Option::is_none")]
    pub entity_model_id: Option<i32>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "custodian_id", skip_serializing_if = "Option::is_none")]
    pub custodian_id: Option<i32>,
}

impl CustodianModelConfig {
    /// CustodianModelConfig model
    pub fn new() -> CustodianModelConfig {
        CustodianModelConfig {
            id: None,
            created_at: None,
            updated_at: None,
            entity_model_id: None,
            active: None,
            custodian_id: None,
        }
    }
}

