/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Custodian : Custodian model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Custodian {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// A unique identifier for Custodian's within SOURSD
    #[serde(rename = "unique_identifier", skip_serializing_if = "Option::is_none")]
    pub unique_identifier: Option<String>,
    #[serde(rename = "contact_email", skip_serializing_if = "Option::is_none")]
    pub contact_email: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "invite_accepted_at", skip_serializing_if = "Option::is_none")]
    pub invite_accepted_at: Option<String>,
    #[serde(rename = "invite_sent_at", skip_serializing_if = "Option::is_none")]
    pub invite_sent_at: Option<String>,
    #[serde(rename = "idvt_required", skip_serializing_if = "Option::is_none")]
    pub idvt_required: Option<bool>,
    #[serde(rename = "gateway_app_id", skip_serializing_if = "Option::is_none")]
    pub gateway_app_id: Option<String>,
    #[serde(rename = "gateway_client_id", skip_serializing_if = "Option::is_none")]
    pub gateway_client_id: Option<String>,
    #[serde(rename = "client_id", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
}

impl Custodian {
    /// Custodian model
    pub fn new() -> Custodian {
        Custodian {
            id: None,
            created_at: None,
            updated_at: None,
            name: None,
            unique_identifier: None,
            contact_email: None,
            enabled: None,
            invite_accepted_at: None,
            invite_sent_at: None,
            idvt_required: None,
            gateway_app_id: None,
            gateway_client_id: None,
            client_id: None,
        }
    }
}

