/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianModelConfigUpdateEntityModelsRequestConfigsInner {
    #[serde(rename = "entity_model_id", skip_serializing_if = "Option::is_none")]
    pub entity_model_id: Option<i32>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl CustodianModelConfigUpdateEntityModelsRequestConfigsInner {
    pub fn new() -> CustodianModelConfigUpdateEntityModelsRequestConfigsInner {
        CustodianModelConfigUpdateEntityModelsRequestConfigsInner {
            entity_model_id: None,
            active: None,
        }
    }
}

