/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInnerAffiliation {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
    #[serde(rename = "organisation", skip_serializing_if = "Option::is_none")]
    pub organisation: Option<Box<models::CustodianGetProjectsUsers200ResponseDataDataInnerAffiliationOrganisation>>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInnerAffiliation {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInnerAffiliation {
        CustodianGetProjectsUsers200ResponseDataDataInnerAffiliation {
            id: None,
            organisation_id: None,
            organisation: None,
        }
    }
}

