/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianProjectOrganisationsUpdateRequest {
    /// Approval status
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<bool>,
    /// Optional comment
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Workflow state
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl CustodianProjectOrganisationsUpdateRequest {
    pub fn new() -> CustodianProjectOrganisationsUpdateRequest {
        CustodianProjectOrganisationsUpdateRequest {
            approved: None,
            comment: None,
            status: None,
        }
    }
}

