/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianProjectOrganisationsGetStatus200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "model_state", skip_serializing_if = "Option::is_none")]
    pub model_state: Option<Box<models::CustodianProjectOrganisationsGetStatus200ResponseDataModelState>>,
}

impl CustodianProjectOrganisationsGetStatus200ResponseData {
    pub fn new() -> CustodianProjectOrganisationsGetStatus200ResponseData {
        CustodianProjectOrganisationsGetStatus200ResponseData {
            id: None,
            name: None,
            model_state: None,
        }
    }
}

