/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianGetProjectsUsers200ResponseDataDataInnerRole {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
}

impl CustodianGetProjectsUsers200ResponseDataDataInnerRole {
    pub fn new() -> CustodianGetProjectsUsers200ResponseDataDataInnerRole {
        CustodianGetProjectsUsers200ResponseDataDataInnerRole {
            id: None,
            name: None,
        }
    }
}

