/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustodianWebhookReceiver : Model representing webhook receivers for custodians
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustodianWebhookReceiver {
    /// Unique identifier for the webhook receiver
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the custodian associated with the webhook receiver
    #[serde(rename = "custodian_id", skip_serializing_if = "Option::is_none")]
    pub custodian_id: Option<i32>,
    /// URL of the webhook receiver
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// ID of the webhook event associated with the receiver
    #[serde(rename = "webhook_event", skip_serializing_if = "Option::is_none")]
    pub webhook_event: Option<i32>,
    /// Timestamp when the webhook receiver was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the webhook receiver was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl CustodianWebhookReceiver {
    /// Model representing webhook receivers for custodians
    pub fn new() -> CustodianWebhookReceiver {
        CustodianWebhookReceiver {
            id: None,
            custodian_id: None,
            url: None,
            webhook_event: None,
            created_at: None,
            updated_at: None,
        }
    }
}

