/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionModel : Model representing decision models
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionModel {
    /// Unique identifier for the decision model
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Type of the model associated with the decision
    #[serde(rename = "model_type")]
    pub model_type: String,
    /// Conditions for the decision model
    #[serde(rename = "conditions")]
    pub conditions: String,
    /// Class defining the rules for the decision model
    #[serde(rename = "rule_class")]
    pub rule_class: String,
    /// Description of the decision model
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ID of the entity model type associated with the decision
    #[serde(rename = "entity_model_type_id", skip_serializing_if = "Option::is_none")]
    pub entity_model_type_id: Option<i32>,
    /// Timestamp when the decision model was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the decision model was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl DecisionModel {
    /// Model representing decision models
    pub fn new(model_type: String, conditions: String, rule_class: String) -> DecisionModel {
        DecisionModel {
            id: None,
            model_type,
            conditions,
            rule_class,
            description: None,
            entity_model_type_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}

