/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DecisionModelType : Model representing types of decision models
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecisionModelType {
    /// Unique identifier for the decision model type
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the decision model type
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Timestamp when the decision model type was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the decision model type was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl DecisionModelType {
    /// Model representing types of decision models
    pub fn new() -> DecisionModelType {
        DecisionModelType {
            id: None,
            name: None,
            created_at: None,
            updated_at: None,
        }
    }
}

