/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Education : Model representing education records
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Education {
    /// Unique identifier for the education record
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Title of the education qualification
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Start date of the education qualification
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<chrono::NaiveDate>,
    /// End date of the education qualification
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<chrono::NaiveDate>,
    /// Name of the educational institute
    #[serde(rename = "institute_name", skip_serializing_if = "Option::is_none")]
    pub institute_name: Option<String>,
    /// Address of the educational institute
    #[serde(rename = "institute_address", skip_serializing_if = "Option::is_none")]
    pub institute_address: Option<String>,
    /// Identifier for the educational institute
    #[serde(rename = "institute_identifier", skip_serializing_if = "Option::is_none")]
    pub institute_identifier: Option<String>,
    /// Source of the education record
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// ID of the registry associated with the education record
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// Timestamp when the education record was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the education record was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Education {
    /// Model representing education records
    pub fn new() -> Education {
        Education {
            id: None,
            title: None,
            from: None,
            to: None,
            institute_name: None,
            institute_address: None,
            institute_identifier: None,
            source: None,
            registry_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}

