/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Endorsement : Model representing endorsements
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Endorsement {
    /// Unique identifier for the endorsement
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the user who reported the endorsement
    #[serde(rename = "reported_by", skip_serializing_if = "Option::is_none")]
    pub reported_by: Option<i32>,
    /// Optional comment provided by the reporter
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// ID of the entity the endorsement is raised against
    #[serde(rename = "raised_against", skip_serializing_if = "Option::is_none")]
    pub raised_against: Option<i32>,
    /// Timestamp when the endorsement was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the endorsement was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Endorsement {
    /// Model representing endorsements
    pub fn new() -> Endorsement {
        Endorsement {
            id: None,
            reported_by: None,
            comment: None,
            raised_against: None,
            created_at: None,
            updated_at: None,
        }
    }
}

