/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndorsementsStore201Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// ID of the created Endorsement entry
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<i32>,
}

impl EndorsementsStore201Response {
    pub fn new() -> EndorsementsStore201Response {
        EndorsementsStore201Response {
            message: None,
            data: None,
        }
    }
}

