/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityModelType : Model representing types of entity models
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityModelType {
    /// Unique identifier for the entity model type
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the entity model type
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Timestamp when the entity model type was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the entity model type was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl EntityModelType {
    /// Model representing types of entity models
    pub fn new() -> EntityModelType {
        EntityModelType {
            id: None,
            name: None,
            created_at: None,
            updated_at: None,
        }
    }
}

