/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EntityModel : Model representing entity models
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityModel {
    /// Unique identifier for the entity model
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the entity model
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of the entity model
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// ID of the entity model type associated with this model
    #[serde(rename = "entity_model_type_id", skip_serializing_if = "Option::is_none")]
    pub entity_model_type_id: Option<i32>,
    /// Indicates whether the model calls a file
    #[serde(rename = "calls_file", skip_serializing_if = "Option::is_none")]
    pub calls_file: Option<bool>,
    /// Path to the file called by the model
    #[serde(rename = "file_path", skip_serializing_if = "Option::is_none")]
    pub file_path: Option<String>,
    /// Indicates whether the model calls an operation
    #[serde(rename = "calls_operation", skip_serializing_if = "Option::is_none")]
    pub calls_operation: Option<bool>,
    /// Operation called by the model
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// Indicates whether the model is active (1 for active, 0 for inactive)
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<i32>,
    /// Timestamp when the entity model was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the entity model was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl EntityModel {
    /// Model representing entity models
    pub fn new() -> EntityModel {
        EntityModel {
            id: None,
            name: None,
            description: None,
            entity_model_type_id: None,
            calls_file: None,
            file_path: None,
            calls_operation: None,
            operation: None,
            active: None,
            created_at: None,
            updated_at: None,
        }
    }
}

