/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryStoreRequest {
    #[serde(rename = "endorsement_id", skip_serializing_if = "Option::is_none")]
    pub endorsement_id: Option<i32>,
    #[serde(rename = "infringement_id", skip_serializing_if = "Option::is_none")]
    pub infringement_id: Option<i32>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "access_key_id", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<i32>,
    #[serde(rename = "custodian_identifier", skip_serializing_if = "Option::is_none")]
    pub custodian_identifier: Option<String>,
}

impl HistoryStoreRequest {
    pub fn new() -> HistoryStoreRequest {
        HistoryStoreRequest {
            endorsement_id: None,
            infringement_id: None,
            project_id: None,
            access_key_id: None,
            custodian_identifier: None,
        }
    }
}

