/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoryIndex200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "endorsement_id", skip_serializing_if = "Option::is_none")]
    pub endorsement_id: Option<i32>,
    #[serde(rename = "infringement_id", skip_serializing_if = "Option::is_none")]
    pub infringement_id: Option<i32>,
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "access_key_id", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<i32>,
    #[serde(rename = "custodian_identifier", skip_serializing_if = "Option::is_none")]
    pub custodian_identifier: Option<String>,
}

impl HistoryIndex200ResponseData {
    pub fn new() -> HistoryIndex200ResponseData {
        HistoryIndex200ResponseData {
            id: None,
            created_at: None,
            updated_at: None,
            endorsement_id: None,
            infringement_id: None,
            project_id: None,
            access_key_id: None,
            custodian_identifier: None,
        }
    }
}

