/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityStoreRequest {
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "selfie_path", skip_serializing_if = "Option::is_none")]
    pub selfie_path: Option<String>,
    #[serde(rename = "passport_path", skip_serializing_if = "Option::is_none")]
    pub passport_path: Option<String>,
    #[serde(rename = "drivers_license_path", skip_serializing_if = "Option::is_none")]
    pub drivers_license_path: Option<String>,
    #[serde(rename = "address_1", skip_serializing_if = "Option::is_none")]
    pub address_1: Option<String>,
    #[serde(rename = "address_2", skip_serializing_if = "Option::is_none")]
    pub address_2: Option<String>,
    #[serde(rename = "town", skip_serializing_if = "Option::is_none")]
    pub town: Option<String>,
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    #[serde(rename = "dob", skip_serializing_if = "Option::is_none")]
    pub dob: Option<String>,
}

impl IdentityStoreRequest {
    pub fn new() -> IdentityStoreRequest {
        IdentityStoreRequest {
            registry_id: None,
            selfie_path: None,
            passport_path: None,
            drivers_license_path: None,
            address_1: None,
            address_2: None,
            town: None,
            county: None,
            country: None,
            postcode: None,
            dob: None,
        }
    }
}

