/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Identity : Model representing identity records
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Identity {
    /// Unique identifier for the identity record
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the registry associated with the identity record
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// First line of the address
    #[serde(rename = "address_1", skip_serializing_if = "Option::is_none")]
    pub address_1: Option<String>,
    /// Second line of the address
    #[serde(rename = "address_2", skip_serializing_if = "Option::is_none")]
    pub address_2: Option<String>,
    /// Town of the address
    #[serde(rename = "town", skip_serializing_if = "Option::is_none")]
    pub town: Option<String>,
    /// County of the address
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    /// Country of the address
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Postcode of the address
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    /// Date of birth
    #[serde(rename = "dob", skip_serializing_if = "Option::is_none")]
    pub dob: Option<chrono::NaiveDate>,
    /// Indicates whether IDVT was successful (1 for success, 0 for failure)
    #[serde(rename = "idvt_success", skip_serializing_if = "Option::is_none")]
    pub idvt_success: Option<i32>,
    /// Identification number from IDVT
    #[serde(rename = "idvt_identification_number", skip_serializing_if = "Option::is_none")]
    pub idvt_identification_number: Option<String>,
    /// Type of document used for IDVT
    #[serde(rename = "idvt_document_type", skip_serializing_if = "Option::is_none")]
    pub idvt_document_type: Option<String>,
    /// Document number used for IDVT
    #[serde(rename = "idvt_document_number", skip_serializing_if = "Option::is_none")]
    pub idvt_document_number: Option<String>,
    /// Country of the document used for IDVT
    #[serde(rename = "idvt_document_country", skip_serializing_if = "Option::is_none")]
    pub idvt_document_country: Option<String>,
    /// Validity date of the document used for IDVT
    #[serde(rename = "idvt_document_valid_until", skip_serializing_if = "Option::is_none")]
    pub idvt_document_valid_until: Option<chrono::NaiveDate>,
    /// First name on the document used for IDVT
    #[serde(rename = "idvt_document_first_name", skip_serializing_if = "Option::is_none")]
    pub idvt_document_first_name: Option<String>,
    /// Last name on the document used for IDVT
    #[serde(rename = "idvt_document_valid_last_name", skip_serializing_if = "Option::is_none")]
    pub idvt_document_valid_last_name: Option<String>,
    /// ID of the IDVT attempt
    #[serde(rename = "idvt_attempt_id", skip_serializing_if = "Option::is_none")]
    pub idvt_attempt_id: Option<String>,
    /// Context ID for IDVT
    #[serde(rename = "idvt_context_id", skip_serializing_if = "Option::is_none")]
    pub idvt_context_id: Option<String>,
    /// Date of birth on the document used for IDVT
    #[serde(rename = "idvt_document_dob", skip_serializing_if = "Option::is_none")]
    pub idvt_document_dob: Option<chrono::NaiveDate>,
    /// Context of the IDVT process
    #[serde(rename = "idvt_context", skip_serializing_if = "Option::is_none")]
    pub idvt_context: Option<String>,
    /// Timestamp when IDVT was completed
    #[serde(rename = "idvt_completed_at", skip_serializing_if = "Option::is_none")]
    pub idvt_completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Result text of the IDVT process
    #[serde(rename = "idvt_result_text", skip_serializing_if = "Option::is_none")]
    pub idvt_result_text: Option<String>,
    /// Timestamp when IDVT was started
    #[serde(rename = "idvt_started_at", skip_serializing_if = "Option::is_none")]
    pub idvt_started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the identity record was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the identity record was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the identity record was deleted
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl Identity {
    /// Model representing identity records
    pub fn new() -> Identity {
        Identity {
            id: None,
            registry_id: None,
            address_1: None,
            address_2: None,
            town: None,
            county: None,
            country: None,
            postcode: None,
            dob: None,
            idvt_success: None,
            idvt_identification_number: None,
            idvt_document_type: None,
            idvt_document_number: None,
            idvt_document_country: None,
            idvt_document_valid_until: None,
            idvt_document_first_name: None,
            idvt_document_valid_last_name: None,
            idvt_attempt_id: None,
            idvt_context_id: None,
            idvt_document_dob: None,
            idvt_context: None,
            idvt_completed_at: None,
            idvt_result_text: None,
            idvt_started_at: None,
            created_at: None,
            updated_at: None,
            deleted_at: None,
        }
    }
}

