/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IdvtPlugin : Model representing IDVT plugins
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdvtPlugin {
    /// Unique identifier for the IDVT plugin
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Function name of the plugin
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,
    /// Arguments passed to the plugin function
    #[serde(rename = "args", skip_serializing_if = "Option::is_none")]
    pub args: Option<String>,
    /// Configuration settings for the plugin
    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
    /// Indicates whether the plugin is enabled (1 for enabled, 0 for disabled)
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<i32>,
    /// Timestamp when the plugin was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the plugin was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl IdvtPlugin {
    /// Model representing IDVT plugins
    pub fn new() -> IdvtPlugin {
        IdvtPlugin {
            id: None,
            function: None,
            args: None,
            config: None,
            enabled: None,
            created_at: None,
            updated_at: None,
        }
    }
}

