/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfringementStoreRequest {
    #[serde(rename = "reported_by", skip_serializing_if = "Option::is_none")]
    pub reported_by: Option<i32>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "raised_against", skip_serializing_if = "Option::is_none")]
    pub raised_against: Option<i32>,
}

impl InfringementStoreRequest {
    pub fn new() -> InfringementStoreRequest {
        InfringementStoreRequest {
            reported_by: None,
            comment: None,
            raised_against: None,
        }
    }
}

