/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InfringementHasResolution : Pivot model representing the relationship between infringements and resolutions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfringementHasResolution {
    /// ID of the infringement
    #[serde(rename = "infringement_id", skip_serializing_if = "Option::is_none")]
    pub infringement_id: Option<i32>,
    /// ID of the resolution
    #[serde(rename = "resolution_id", skip_serializing_if = "Option::is_none")]
    pub resolution_id: Option<i32>,
}

impl InfringementHasResolution {
    /// Pivot model representing the relationship between infringements and resolutions
    pub fn new() -> InfringementHasResolution {
        InfringementHasResolution {
            infringement_id: None,
            resolution_id: None,
        }
    }
}

