/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelState : Model representing the state of a model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelState {
    /// Unique identifier for the model state
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the state associated with the model state
    #[serde(rename = "state_id", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<i32>,
    /// Type of the model associated with the state
    #[serde(rename = "stateable_type", skip_serializing_if = "Option::is_none")]
    pub stateable_type: Option<String>,
    /// ID of the model associated with the state
    #[serde(rename = "stateable_id", skip_serializing_if = "Option::is_none")]
    pub stateable_id: Option<i32>,
    /// Timestamp when the model state was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the model state was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ModelState {
    /// Model representing the state of a model
    pub fn new() -> ModelState {
        ModelState {
            id: None,
            state_id: None,
            stateable_type: None,
            stateable_id: None,
            created_at: None,
            updated_at: None,
        }
    }
}

