/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsGetUserNotifications200ResponseDataInnerData {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl NotificationsGetUserNotifications200ResponseDataInnerData {
    pub fn new() -> NotificationsGetUserNotifications200ResponseDataInnerData {
        NotificationsGetUserNotifications200ResponseDataInnerData {
            message: None,
            time: None,
        }
    }
}

