/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsGetNotificationCounts200ResponseData {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<i32>,
    #[serde(rename = "unread", skip_serializing_if = "Option::is_none")]
    pub unread: Option<i32>,
}

impl NotificationsGetNotificationCounts200ResponseData {
    pub fn new() -> NotificationsGetNotificationCounts200ResponseData {
        NotificationsGetNotificationCounts200ResponseData {
            total: None,
            read: None,
            unread: None,
        }
    }
}

