/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationsGetUserNotifications200ResponseDataInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "notifiable_type", skip_serializing_if = "Option::is_none")]
    pub notifiable_type: Option<String>,
    #[serde(rename = "notifiable_id", skip_serializing_if = "Option::is_none")]
    pub notifiable_id: Option<i32>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::NotificationsGetUserNotifications200ResponseDataInnerData>>,
    #[serde(rename = "read_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub read_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl NotificationsGetUserNotifications200ResponseDataInner {
    pub fn new() -> NotificationsGetUserNotifications200ResponseDataInner {
        NotificationsGetUserNotifications200ResponseDataInner {
            id: None,
            r#type: None,
            notifiable_type: None,
            notifiable_id: None,
            data: None,
            read_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}

