/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Organisation : Organisation model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organisation {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "organisation_name", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<String>,
    #[serde(rename = "address_1", skip_serializing_if = "Option::is_none")]
    pub address_1: Option<String>,
    #[serde(rename = "address_2", skip_serializing_if = "Option::is_none")]
    pub address_2: Option<String>,
    #[serde(rename = "town", skip_serializing_if = "Option::is_none")]
    pub town: Option<String>,
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    #[serde(rename = "lead_applicant_organisation_name", skip_serializing_if = "Option::is_none")]
    pub lead_applicant_organisation_name: Option<String>,
    #[serde(rename = "lead_applicant_email", skip_serializing_if = "Option::is_none")]
    pub lead_applicant_email: Option<String>,
    #[serde(rename = "organisation_unique_id", skip_serializing_if = "Option::is_none")]
    pub organisation_unique_id: Option<String>,
    #[serde(rename = "applicant_names", skip_serializing_if = "Option::is_none")]
    pub applicant_names: Option<String>,
    #[serde(rename = "funders_and_sponsors", skip_serializing_if = "Option::is_none")]
    pub funders_and_sponsors: Option<String>,
    #[serde(rename = "sub_license_arrangements", skip_serializing_if = "Option::is_none")]
    pub sub_license_arrangements: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "dsptk_ods_code", skip_serializing_if = "Option::is_none")]
    pub dsptk_ods_code: Option<String>,
    #[serde(rename = "dsptk_certified", skip_serializing_if = "Option::is_none")]
    pub dsptk_certified: Option<bool>,
    #[serde(rename = "dsptk_expiry_date", skip_serializing_if = "Option::is_none")]
    pub dsptk_expiry_date: Option<String>,
    #[serde(rename = "iso_27001_certified", skip_serializing_if = "Option::is_none")]
    pub iso_27001_certified: Option<bool>,
    #[serde(rename = "iso_27001_certification_num", skip_serializing_if = "Option::is_none")]
    pub iso_27001_certification_num: Option<String>,
    #[serde(rename = "iso_expiry_date", skip_serializing_if = "Option::is_none")]
    pub iso_expiry_date: Option<String>,
    #[serde(rename = "ce_certified", skip_serializing_if = "Option::is_none")]
    pub ce_certified: Option<bool>,
    #[serde(rename = "ce_certification_num", skip_serializing_if = "Option::is_none")]
    pub ce_certification_num: Option<String>,
    #[serde(rename = "ce_expiry_date", skip_serializing_if = "Option::is_none")]
    pub ce_expiry_date: Option<String>,
    #[serde(rename = "ce_plus_certified", skip_serializing_if = "Option::is_none")]
    pub ce_plus_certified: Option<bool>,
    #[serde(rename = "ce_plus_certification_num", skip_serializing_if = "Option::is_none")]
    pub ce_plus_certification_num: Option<String>,
    #[serde(rename = "ce_plus_expiry_date", skip_serializing_if = "Option::is_none")]
    pub ce_plus_expiry_date: Option<String>,
    /// True if either CE or ISO 27001 certification is currently valid
    #[serde(rename = "ce_or_iso_certified", skip_serializing_if = "Option::is_none")]
    pub ce_or_iso_certified: Option<bool>,
    /// True if either CE+ or ISO 27001 certification is currently valid
    #[serde(rename = "ce_plus_or_iso_certified", skip_serializing_if = "Option::is_none")]
    pub ce_plus_or_iso_certified: Option<bool>,
    #[serde(rename = "idvt_result", skip_serializing_if = "Option::is_none")]
    pub idvt_result: Option<i32>,
    #[serde(rename = "idvt_result_perc", skip_serializing_if = "Option::is_none")]
    pub idvt_result_perc: Option<i32>,
    #[serde(rename = "idvt_errors", skip_serializing_if = "Option::is_none")]
    pub idvt_errors: Option<String>,
    #[serde(rename = "idvt_completed_at", skip_serializing_if = "Option::is_none")]
    pub idvt_completed_at: Option<String>,
    #[serde(rename = "companies_house_no", skip_serializing_if = "Option::is_none")]
    pub companies_house_no: Option<String>,
    #[serde(rename = "sector_id", skip_serializing_if = "Option::is_none")]
    pub sector_id: Option<i32>,
    /// ROR.org identification for Research Organisations
    #[serde(rename = "ror_id", skip_serializing_if = "Option::is_none")]
    pub ror_id: Option<String>,
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Declaration of small/medium business
    #[serde(rename = "smb_status", skip_serializing_if = "Option::is_none")]
    pub smb_status: Option<bool>,
    /// Organisation size. Integer denotes list index rather than absolute value
    #[serde(rename = "organisation_size", skip_serializing_if = "Option::is_none")]
    pub organisation_size: Option<i32>,
    /// Unclaimed
    #[serde(rename = "unclaimed", skip_serializing_if = "Option::is_none")]
    pub unclaimed: Option<bool>,
    /// Whether this Organisation has been approved to use the system or not
    #[serde(rename = "system_approved", skip_serializing_if = "Option::is_none")]
    pub system_approved: Option<bool>,
    #[serde(rename = "ods_id", skip_serializing_if = "Option::is_none")]
    pub ods_id: Option<String>,
    #[serde(rename = "dsptk_status", skip_serializing_if = "Option::is_none")]
    pub dsptk_status: Option<String>,
    #[serde(rename = "dsptk_date_last_published", skip_serializing_if = "Option::is_none")]
    pub dsptk_date_last_published: Option<String>,
    #[serde(rename = "ico_registration_id", skip_serializing_if = "Option::is_none")]
    pub ico_registration_id: Option<String>,
    #[serde(rename = "ico_date_registered", skip_serializing_if = "Option::is_none")]
    pub ico_date_registered: Option<String>,
    #[serde(rename = "ico_expiry_date", skip_serializing_if = "Option::is_none")]
    pub ico_expiry_date: Option<String>,
}

impl Organisation {
    /// Organisation model
    pub fn new() -> Organisation {
        Organisation {
            id: None,
            created_at: None,
            updated_at: None,
            organisation_name: None,
            address_1: None,
            address_2: None,
            town: None,
            county: None,
            country: None,
            postcode: None,
            lead_applicant_organisation_name: None,
            lead_applicant_email: None,
            organisation_unique_id: None,
            applicant_names: None,
            funders_and_sponsors: None,
            sub_license_arrangements: None,
            verified: None,
            dsptk_ods_code: None,
            dsptk_certified: None,
            dsptk_expiry_date: None,
            iso_27001_certified: None,
            iso_27001_certification_num: None,
            iso_expiry_date: None,
            ce_certified: None,
            ce_certification_num: None,
            ce_expiry_date: None,
            ce_plus_certified: None,
            ce_plus_certification_num: None,
            ce_plus_expiry_date: None,
            ce_or_iso_certified: None,
            ce_plus_or_iso_certified: None,
            idvt_result: None,
            idvt_result_perc: None,
            idvt_errors: None,
            idvt_completed_at: None,
            companies_house_no: None,
            sector_id: None,
            ror_id: None,
            website: None,
            smb_status: None,
            organisation_size: None,
            unclaimed: None,
            system_approved: None,
            ods_id: None,
            dsptk_status: None,
            dsptk_date_last_published: None,
            ico_registration_id: None,
            ico_date_registered: None,
            ico_expiry_date: None,
        }
    }
}

