/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganisationsIdvt200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "idvt_result", skip_serializing_if = "Option::is_none")]
    pub idvt_result: Option<bool>,
    #[serde(rename = "idvt_result_perc", skip_serializing_if = "Option::is_none")]
    pub idvt_result_perc: Option<f64>,
    #[serde(rename = "idvt_errors", skip_serializing_if = "Option::is_none")]
    pub idvt_errors: Option<serde_json::Value>,
    #[serde(rename = "idvt_completed_at", skip_serializing_if = "Option::is_none")]
    pub idvt_completed_at: Option<String>,
}

impl OrganisationsIdvt200ResponseData {
    pub fn new() -> OrganisationsIdvt200ResponseData {
        OrganisationsIdvt200ResponseData {
            id: None,
            idvt_result: None,
            idvt_result_perc: None,
            idvt_errors: None,
            idvt_completed_at: None,
        }
    }
}

