/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrganisationsGetRegistries200ResponseDataDataInner {
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
}

impl OrganisationsGetRegistries200ResponseDataDataInner {
    pub fn new() -> OrganisationsGetRegistries200ResponseDataDataInner {
        OrganisationsGetRegistries200ResponseDataDataInner {
            registry_id: None,
            organisation_id: None,
        }
    }
}

