/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectGetProjectUsers200ResponseDataInnerRegistry {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<bool>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::ProjectGetProjectUsers200ResponseDataInnerRegistryUser>>,
    #[serde(rename = "organisations", skip_serializing_if = "Option::is_none")]
    pub organisations: Option<Vec<models::ProjectGetProjectUsers200ResponseDataInnerRegistryOrganisationsInner>>,
    #[serde(rename = "affiliation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub affiliation: Option<Option<Box<models::ProjectGetProjectUsers200ResponseDataInnerRegistryAffiliation>>>,
}

impl ProjectGetProjectUsers200ResponseDataInnerRegistry {
    pub fn new() -> ProjectGetProjectUsers200ResponseDataInnerRegistry {
        ProjectGetProjectUsers200ResponseDataInnerRegistry {
            id: None,
            created_at: None,
            updated_at: None,
            verified: None,
            user: None,
            organisations: None,
            affiliation: None,
        }
    }
}

