/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectMakePrimaryContact200ResponseDataInner {
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    #[serde(rename = "user_digital_ident", skip_serializing_if = "Option::is_none")]
    pub user_digital_ident: Option<String>,
    #[serde(rename = "registry", skip_serializing_if = "Option::is_none")]
    pub registry: Option<Box<models::ProjectMakePrimaryContact200ResponseDataInnerRegistry>>,
}

impl ProjectMakePrimaryContact200ResponseDataInner {
    pub fn new() -> ProjectMakePrimaryContact200ResponseDataInner {
        ProjectMakePrimaryContact200ResponseDataInner {
            project_id: None,
            user_digital_ident: None,
            registry: None,
        }
    }
}

