/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectUsersBulkInviteProjectUsersRequestUsersInner {
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "emailAddress", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(rename = "projectRole", skip_serializing_if = "Option::is_none")]
    pub project_role: Option<ProjectRole>,
    #[serde(rename = "organisationId", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
}

impl ProjectUsersBulkInviteProjectUsersRequestUsersInner {
    pub fn new() -> ProjectUsersBulkInviteProjectUsersRequestUsersInner {
        ProjectUsersBulkInviteProjectUsersRequestUsersInner {
            first_name: None,
            last_name: None,
            email_address: None,
            project_role: None,
            organisation_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProjectRole {
    #[serde(rename = "Principal Investigator (PI)")]
    PrincipalInvestigatorLeftParenthesisPiRightParenthesis,
    #[serde(rename = "Co-Investigator (Co-I) / Sub-Investigator (Sub-I)")]
    CoInvestigatorLeftParenthesisCoIRightParenthesisSlashSubInvestigatorLeftParenthesisSubIRightParenthesis,
    #[serde(rename = "Data Analyst")]
    DataAnalyst,
    #[serde(rename = "Data Engineer")]
    DataEngineer,
    #[serde(rename = "Postdoc")]
    Postdoc,
    #[serde(rename = "Research Fellow")]
    ResearchFellow,
    #[serde(rename = "Researcher")]
    Researcher,
    #[serde(rename = "Student")]
    Student,
}

impl Default for ProjectRole {
    fn default() -> ProjectRole {
        Self::PrincipalInvestigatorLeftParenthesisPiRightParenthesis
    }
}

