/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Project : Project model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Project {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "unique_id", skip_serializing_if = "Option::is_none")]
    pub unique_id: Option<String>,
    #[serde(rename = "lay_summary", skip_serializing_if = "Option::is_none")]
    pub lay_summary: Option<String>,
    /// A unique identifier for Custodian's within SOURSD
    #[serde(rename = "public_benefit", skip_serializing_if = "Option::is_none")]
    pub public_benefit: Option<String>,
    #[serde(rename = "request_category_type", skip_serializing_if = "Option::is_none")]
    pub request_category_type: Option<String>,
    #[serde(rename = "technical_summary", skip_serializing_if = "Option::is_none")]
    pub technical_summary: Option<String>,
    #[serde(rename = "other_approval_commitees", skip_serializing_if = "Option::is_none")]
    pub other_approval_commitees: Option<String>,
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
}

impl Project {
    /// Project model
    pub fn new() -> Project {
        Project {
            id: None,
            title: None,
            unique_id: None,
            lay_summary: None,
            public_benefit: None,
            request_category_type: None,
            technical_summary: None,
            other_approval_commitees: None,
            start_date: None,
            end_date: None,
        }
    }
}

