/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ProjectHasCustodian : Pivot model representing the relationship between projects and custodians
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectHasCustodian {
    /// Unique identifier for the project-custodian relationship
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the project
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    /// ID of the custodian
    #[serde(rename = "custodian_id", skip_serializing_if = "Option::is_none")]
    pub custodian_id: Option<i32>,
    /// Indicates whether the custodian is approved for the project (1 for approved, 0 for not approved)
    #[serde(rename = "approved", skip_serializing_if = "Option::is_none")]
    pub approved: Option<i32>,
}

impl ProjectHasCustodian {
    /// Pivot model representing the relationship between projects and custodians
    pub fn new() -> ProjectHasCustodian {
        ProjectHasCustodian {
            id: None,
            project_id: None,
            custodian_id: None,
            approved: None,
        }
    }
}

