/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectHasUser {
    #[serde(rename = "project", skip_serializing_if = "Option::is_none")]
    pub project: Option<Box<models::Project>>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<Box<models::ProjectRole>>,
    #[serde(rename = "affiliation", skip_serializing_if = "Option::is_none")]
    pub affiliation: Option<Box<models::Affiliation>>,
}

impl ProjectHasUser {
    pub fn new() -> ProjectHasUser {
        ProjectHasUser {
            project: None,
            role: None,
            affiliation: None,
        }
    }
}

