/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectStoreRequest {
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "public_benefit", skip_serializing_if = "Option::is_none")]
    pub public_benefit: Option<String>,
    #[serde(rename = "runs_to", skip_serializing_if = "Option::is_none")]
    pub runs_to: Option<String>,
}

impl ProjectStoreRequest {
    pub fn new() -> ProjectStoreRequest {
        ProjectStoreRequest {
            registry_id: None,
            name: None,
            public_benefit: None,
            runs_to: None,
        }
    }
}

