/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectUpdateAllProjectUsersRequestUsersInner {
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "affiliation_id", skip_serializing_if = "Option::is_none")]
    pub affiliation_id: Option<i32>,
    #[serde(rename = "project_user_id", skip_serializing_if = "Option::is_none")]
    pub project_user_id: Option<i32>,
    #[serde(rename = "primary_contact", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_contact: Option<Option<bool>>,
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<Box<models::ProjectUpdateAllProjectUsersRequestUsersInnerRole>>>,
}

impl ProjectUpdateAllProjectUsersRequestUsersInner {
    pub fn new() -> ProjectUpdateAllProjectUsersRequestUsersInner {
        ProjectUpdateAllProjectUsersRequestUsersInner {
            registry_id: None,
            affiliation_id: None,
            project_user_id: None,
            primary_contact: None,
            role: None,
        }
    }
}

