/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectGetProjectUsers200ResponseDataInnerRegistryAffiliation {
    #[serde(rename = "relationship", skip_serializing_if = "Option::is_none")]
    pub relationship: Option<String>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "department", skip_serializing_if = "Option::is_none")]
    pub department: Option<String>,
    #[serde(rename = "role", skip_serializing_if = "Option::is_none")]
    pub role: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "ror", skip_serializing_if = "Option::is_none")]
    pub ror: Option<String>,
}

impl ProjectGetProjectUsers200ResponseDataInnerRegistryAffiliation {
    pub fn new() -> ProjectGetProjectUsers200ResponseDataInnerRegistryAffiliation {
        ProjectGetProjectUsers200ResponseDataInnerRegistryAffiliation {
            relationship: None,
            from: None,
            to: None,
            department: None,
            role: None,
            email: None,
            ror: None,
        }
    }
}

