/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProjectGetProjectUsers200ResponseDataInnerRegistryUser {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "user_group", skip_serializing_if = "Option::is_none")]
    pub user_group: Option<String>,
    #[serde(rename = "consent_scrape", skip_serializing_if = "Option::is_none")]
    pub consent_scrape: Option<bool>,
    #[serde(rename = "public_opt_in", skip_serializing_if = "Option::is_none")]
    pub public_opt_in: Option<bool>,
}

impl ProjectGetProjectUsers200ResponseDataInnerRegistryUser {
    pub fn new() -> ProjectGetProjectUsers200ResponseDataInnerRegistryUser {
        ProjectGetProjectUsers200ResponseDataInnerRegistryUser {
            id: None,
            first_name: None,
            last_name: None,
            email: None,
            registry_id: None,
            created_at: None,
            updated_at: None,
            user_group: None,
            consent_scrape: None,
            public_opt_in: None,
        }
    }
}

