/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryQuery200ResponseData {
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::QueryQuery200ResponseDataUser>>,
    #[serde(rename = "registry", skip_serializing_if = "Option::is_none")]
    pub registry: Option<Box<models::QueryQuery200ResponseDataRegistry>>,
    /// Projects the queried user is linked to, scoped to the requesting custodian
    #[serde(rename = "projects", skip_serializing_if = "Option::is_none")]
    pub projects: Option<Vec<models::QueryQuery200ResponseDataProjectsInner>>,
}

impl QueryQuery200ResponseData {
    pub fn new() -> QueryQuery200ResponseData {
        QueryQuery200ResponseData {
            user: None,
            registry: None,
            projects: None,
        }
    }
}

