/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryQuery200ResponseDataRegistryAllOfHistoryInner {
    /// Unique identifier for the history record
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the affiliation associated with the history record
    #[serde(rename = "affiliation_id", skip_serializing_if = "Option::is_none")]
    pub affiliation_id: Option<i32>,
    /// ID of the endorsement associated with the history record
    #[serde(rename = "endorsement_id", skip_serializing_if = "Option::is_none")]
    pub endorsement_id: Option<i32>,
    /// ID of the infringement associated with the history record
    #[serde(rename = "infringement_id", skip_serializing_if = "Option::is_none")]
    pub infringement_id: Option<i32>,
    /// ID of the project associated with the history record
    #[serde(rename = "project_id", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<i32>,
    /// ID of the access key associated with the history record
    #[serde(rename = "access_key_id", skip_serializing_if = "Option::is_none")]
    pub access_key_id: Option<i32>,
    /// Identifier for the custodian associated with the history record
    #[serde(rename = "custodian_identifier", skip_serializing_if = "Option::is_none")]
    pub custodian_identifier: Option<String>,
    /// Hash of the ledger associated with the history record
    #[serde(rename = "ledger_hash", skip_serializing_if = "Option::is_none")]
    pub ledger_hash: Option<String>,
    /// Timestamp when the history record was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the history record was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "affiliation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub affiliation: Option<Option<Box<models::Affiliation>>>,
    #[serde(rename = "project", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project: Option<Option<Box<models::Project>>>,
}

impl QueryQuery200ResponseDataRegistryAllOfHistoryInner {
    pub fn new() -> QueryQuery200ResponseDataRegistryAllOfHistoryInner {
        QueryQuery200ResponseDataRegistryAllOfHistoryInner {
            id: None,
            affiliation_id: None,
            endorsement_id: None,
            infringement_id: None,
            project_id: None,
            access_key_id: None,
            custodian_identifier: None,
            ledger_hash: None,
            created_at: None,
            updated_at: None,
            affiliation: None,
            project: None,
        }
    }
}

