/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueryQuery200ResponseDataRegistry : The matched Registry record
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryQuery200ResponseDataRegistry {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
    #[serde(rename = "digi_ident", skip_serializing_if = "Option::is_none")]
    pub digi_ident: Option<String>,
    #[serde(rename = "dl_ident", skip_serializing_if = "Option::is_none")]
    pub dl_ident: Option<String>,
    #[serde(rename = "pp_ident", skip_serializing_if = "Option::is_none")]
    pub pp_ident: Option<String>,
    #[serde(rename = "verified", skip_serializing_if = "Option::is_none")]
    pub verified: Option<i32>,
    /// Training records linked to the registry
    #[serde(rename = "training", skip_serializing_if = "Option::is_none")]
    pub training: Option<Vec<models::Training>>,
    /// History records linked to the registry, each with its related affiliation and project
    #[serde(rename = "history", skip_serializing_if = "Option::is_none")]
    pub history: Option<Vec<models::QueryQuery200ResponseDataRegistryAllOfHistoryInner>>,
}

impl QueryQuery200ResponseDataRegistry {
    /// The matched Registry record
    pub fn new() -> QueryQuery200ResponseDataRegistry {
        QueryQuery200ResponseDataRegistry {
            id: None,
            created_at: None,
            updated_at: None,
            deleted_at: None,
            digi_ident: None,
            dl_ident: None,
            pp_ident: None,
            verified: None,
            training: None,
            history: None,
        }
    }
}

