/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistryHasProfessionalRegistration : Pivot model representing the relationship between registries and professional registrations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryHasProfessionalRegistration {
    /// Unique identifier for the registry-professional registration relationship
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the registry
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// ID of the professional registration
    #[serde(rename = "professional_registration_id", skip_serializing_if = "Option::is_none")]
    pub professional_registration_id: Option<i32>,
}

impl RegistryHasProfessionalRegistration {
    /// Pivot model representing the relationship between registries and professional registrations
    pub fn new() -> RegistryHasProfessionalRegistration {
        RegistryHasProfessionalRegistration {
            id: None,
            registry_id: None,
            professional_registration_id: None,
        }
    }
}

