/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistryHasEducation : Pivot model representing the relationship between registries and educations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryHasEducation {
    /// ID of the registry
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// ID of the education
    #[serde(rename = "education_id", skip_serializing_if = "Option::is_none")]
    pub education_id: Option<i32>,
}

impl RegistryHasEducation {
    /// Pivot model representing the relationship between registries and educations
    pub fn new() -> RegistryHasEducation {
        RegistryHasEducation {
            registry_id: None,
            education_id: None,
        }
    }
}

