/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistryHasTraining : Pivot model representing the relationship between registries and trainings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryHasTraining {
    /// ID of the registry
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// ID of the training
    #[serde(rename = "training_id", skip_serializing_if = "Option::is_none")]
    pub training_id: Option<i32>,
}

impl RegistryHasTraining {
    /// Pivot model representing the relationship between registries and trainings
    pub fn new() -> RegistryHasTraining {
        RegistryHasTraining {
            registry_id: None,
            training_id: None,
        }
    }
}

