/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegistryHasAffiliation : Pivot model representing the relationship between registries and affiliations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegistryHasAffiliation {
    /// Unique identifier for the registry-affiliation relationship
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the registry
    #[serde(rename = "registry_id", skip_serializing_if = "Option::is_none")]
    pub registry_id: Option<i32>,
    /// ID of the affiliation
    #[serde(rename = "affiliation_id", skip_serializing_if = "Option::is_none")]
    pub affiliation_id: Option<i32>,
}

impl RegistryHasAffiliation {
    /// Pivot model representing the relationship between registries and affiliations
    pub fn new() -> RegistryHasAffiliation {
        RegistryHasAffiliation {
            id: None,
            registry_id: None,
            affiliation_id: None,
        }
    }
}

