/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SsoTenant : An enterprise customer's SAML Identity Provider connection
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SsoTenant {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "idp_alias", skip_serializing_if = "Option::is_none")]
    pub idp_alias: Option<String>,
    #[serde(rename = "metadata_url", skip_serializing_if = "Option::is_none")]
    pub metadata_url: Option<String>,
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    #[serde(rename = "metadata_imported_at", skip_serializing_if = "Option::is_none")]
    pub metadata_imported_at: Option<String>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Keycloak's own SP entity ID - null until approved. Register this as the SAML Identifier on the customer's IdP.
    #[serde(rename = "sp_entity_id", skip_serializing_if = "Option::is_none")]
    pub sp_entity_id: Option<String>,
    /// Keycloak's ACS/reply URL for this tenant - null until approved.
    #[serde(rename = "sp_acs_url", skip_serializing_if = "Option::is_none")]
    pub sp_acs_url: Option<String>,
    /// Downloadable SP metadata descriptor most IdPs can import directly - null until approved.
    #[serde(rename = "sp_metadata_url", skip_serializing_if = "Option::is_none")]
    pub sp_metadata_url: Option<String>,
    /// One of pending, approved, rejected
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// ID of the user who submitted this tenant for approval
    #[serde(rename = "submitted_by_user_id", skip_serializing_if = "Option::is_none")]
    pub submitted_by_user_id: Option<i32>,
    /// Reason given when status is rejected - null otherwise
    #[serde(rename = "rejected_reason", skip_serializing_if = "Option::is_none")]
    pub rejected_reason: Option<String>,
}

impl SsoTenant {
    /// An enterprise customer's SAML Identity Provider connection
    pub fn new() -> SsoTenant {
        SsoTenant {
            id: None,
            created_at: None,
            updated_at: None,
            name: None,
            idp_alias: None,
            metadata_url: None,
            entity_id: None,
            metadata_imported_at: None,
            enabled: None,
            sp_entity_id: None,
            sp_acs_url: None,
            sp_metadata_url: None,
            status: None,
            submitted_by_user_id: None,
            rejected_reason: None,
        }
    }
}

