/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Subsidiary : Model representing subsidiaries
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subsidiary {
    /// Unique identifier for the subsidiary
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Name of the subsidiary
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Primary address line of the subsidiary
    #[serde(rename = "address_1", skip_serializing_if = "Option::is_none")]
    pub address_1: Option<String>,
    /// Secondary address line of the subsidiary
    #[serde(rename = "address_2", skip_serializing_if = "Option::is_none")]
    pub address_2: Option<String>,
    /// Town where the subsidiary is located
    #[serde(rename = "town", skip_serializing_if = "Option::is_none")]
    pub town: Option<String>,
    /// County where the subsidiary is located
    #[serde(rename = "county", skip_serializing_if = "Option::is_none")]
    pub county: Option<String>,
    /// Country where the subsidiary is located
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Postcode of the subsidiary
    #[serde(rename = "postcode", skip_serializing_if = "Option::is_none")]
    pub postcode: Option<String>,
    /// Website of the subsidiary
    #[serde(rename = "website", skip_serializing_if = "Option::is_none")]
    pub website: Option<String>,
    /// Indicates if the subsidiary is a parent company
    #[serde(rename = "is_parent", skip_serializing_if = "Option::is_none")]
    pub is_parent: Option<i32>,
}

impl Subsidiary {
    /// Model representing subsidiaries
    pub fn new() -> Subsidiary {
        Subsidiary {
            id: None,
            name: None,
            address_1: None,
            address_2: None,
            town: None,
            county: None,
            country: None,
            postcode: None,
            website: None,
            is_parent: None,
        }
    }
}

