/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TrainingHasFile : Pivot model representing the relationship between trainings and files
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrainingHasFile {
    /// ID of the training
    #[serde(rename = "training_id", skip_serializing_if = "Option::is_none")]
    pub training_id: Option<i32>,
    /// ID of the file
    #[serde(rename = "file_id", skip_serializing_if = "Option::is_none")]
    pub file_id: Option<i32>,
}

impl TrainingHasFile {
    /// Pivot model representing the relationship between trainings and files
    pub fn new() -> TrainingHasFile {
        TrainingHasFile {
            training_id: None,
            file_id: None,
        }
    }
}

