/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UksaLiveFeed : Model representing UKSA live feed data
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UksaLiveFeed {
    /// Unique identifier for the UKSA live feed record
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// First name of the individual
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Last name of the individual
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Name of the organisation
    #[serde(rename = "organisation_name", skip_serializing_if = "Option::is_none")]
    pub organisation_name: Option<String>,
    /// Accreditation number
    #[serde(rename = "accreditation_number", skip_serializing_if = "Option::is_none")]
    pub accreditation_number: Option<String>,
    /// Type of accreditation
    #[serde(rename = "accreditation_type", skip_serializing_if = "Option::is_none")]
    pub accreditation_type: Option<String>,
    /// Expiry date of the accreditation
    #[serde(rename = "expiry_date", skip_serializing_if = "Option::is_none")]
    pub expiry_date: Option<chrono::NaiveDate>,
    /// Indicates whether the record is public
    #[serde(rename = "public_record", skip_serializing_if = "Option::is_none")]
    pub public_record: Option<String>,
    /// Current stage of the accreditation process
    #[serde(rename = "stage", skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    /// Timestamp when the record was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the record was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl UksaLiveFeed {
    /// Model representing UKSA live feed data
    pub fn new() -> UksaLiveFeed {
        UksaLiveFeed {
            id: None,
            first_name: None,
            last_name: None,
            organisation_name: None,
            accreditation_number: None,
            accreditation_type: None,
            expiry_date: None,
            public_record: None,
            stage: None,
            created_at: None,
            updated_at: None,
        }
    }
}

