/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserIndex200ResponseData {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "first_name", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    #[serde(rename = "last_name", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "email_verified_at", skip_serializing_if = "Option::is_none")]
    pub email_verified_at: Option<String>,
    #[serde(rename = "consent_scrape", skip_serializing_if = "Option::is_none")]
    pub consent_scrape: Option<bool>,
    #[serde(rename = "public_opt_in", skip_serializing_if = "Option::is_none")]
    pub public_opt_in: Option<bool>,
    #[serde(rename = "declaration_signed", skip_serializing_if = "Option::is_none")]
    pub declaration_signed: Option<bool>,
    #[serde(rename = "organisation_id", skip_serializing_if = "Option::is_none")]
    pub organisation_id: Option<i32>,
    #[serde(rename = "orcid_scanning", skip_serializing_if = "Option::is_none")]
    pub orcid_scanning: Option<i32>,
    #[serde(rename = "orcid_scanning_completed_at", skip_serializing_if = "Option::is_none")]
    pub orcid_scanning_completed_at: Option<String>,
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<String>,
    #[serde(rename = "t_and_c_agreed", skip_serializing_if = "Option::is_none")]
    pub t_and_c_agreed: Option<bool>,
    #[serde(rename = "t_and_c_agreement_date", skip_serializing_if = "Option::is_none")]
    pub t_and_c_agreement_date: Option<String>,
    #[serde(rename = "uksa_registered", skip_serializing_if = "Option::is_none")]
    pub uksa_registered: Option<bool>,
    #[serde(rename = "is_sro", skip_serializing_if = "Option::is_none")]
    pub is_sro: Option<bool>,
}

impl UserIndex200ResponseData {
    pub fn new() -> UserIndex200ResponseData {
        UserIndex200ResponseData {
            id: None,
            created_at: None,
            updated_at: None,
            first_name: None,
            last_name: None,
            email: None,
            email_verified_at: None,
            consent_scrape: None,
            public_opt_in: None,
            declaration_signed: None,
            organisation_id: None,
            orcid_scanning: None,
            orcid_scanning_completed_at: None,
            location: None,
            t_and_c_agreed: None,
            t_and_c_agreement_date: None,
            uksa_registered: None,
            is_sro: None,
        }
    }
}

