/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserHasCustodianPermission : Pivot model representing the relationship between users, custodians, and permissions
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserHasCustodianPermission {
    /// ID of the user
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// ID of the permission
    #[serde(rename = "permission_id", skip_serializing_if = "Option::is_none")]
    pub permission_id: Option<i32>,
    /// ID of the custodian
    #[serde(rename = "custodian_id", skip_serializing_if = "Option::is_none")]
    pub custodian_id: Option<i32>,
}

impl UserHasCustodianPermission {
    /// Pivot model representing the relationship between users, custodians, and permissions
    pub fn new() -> UserHasCustodianPermission {
        UserHasCustodianPermission {
            user_id: None,
            permission_id: None,
            custodian_id: None,
        }
    }
}

