/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationLog : Validation Log model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationLog {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Type of the primary entity associated with the validation log
    #[serde(rename = "entity_type", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<String>,
    /// ID of the primary entity associated with the validation log
    #[serde(rename = "entity_id", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<i32>,
    /// Type of the secondary entity associated with the validation log
    #[serde(rename = "secondary_entity_type", skip_serializing_if = "Option::is_none")]
    pub secondary_entity_type: Option<String>,
    /// ID of the secondary entity associated with the validation log
    #[serde(rename = "secondary_entity_id", skip_serializing_if = "Option::is_none")]
    pub secondary_entity_id: Option<i32>,
    /// Type of the tertiary entity associated with the validation log
    #[serde(rename = "tertiary_entity_type", skip_serializing_if = "Option::is_none")]
    pub tertiary_entity_type: Option<String>,
    /// ID of the tertiary entity associated with the validation log
    #[serde(rename = "tertiary_entity_id", skip_serializing_if = "Option::is_none")]
    pub tertiary_entity_id: Option<i32>,
    /// Name of the validation log entry
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Timestamp when the validation was completed (nullable)
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Whether the validation was manually confirmed
    #[serde(rename = "manually_confirmed", skip_serializing_if = "Option::is_none")]
    pub manually_confirmed: Option<bool>,
}

impl ValidationLog {
    /// Validation Log model
    pub fn new() -> ValidationLog {
        ValidationLog {
            id: None,
            entity_type: None,
            entity_id: None,
            secondary_entity_type: None,
            secondary_entity_id: None,
            tertiary_entity_type: None,
            tertiary_entity_id: None,
            name: None,
            completed_at: None,
            manually_confirmed: None,
        }
    }
}

