/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ValidationLogComment : Comments on validation logs
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationLogComment {
    /// Model primary key
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// ID of the associated validation log
    #[serde(rename = "validation_log_id", skip_serializing_if = "Option::is_none")]
    pub validation_log_id: Option<i32>,
    /// ID of the user who made the comment
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i32>,
    /// The comment text
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    /// Timestamp when the comment was created
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Timestamp when the comment was last updated
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl ValidationLogComment {
    /// Comments on validation logs
    pub fn new() -> ValidationLogComment {
        ValidationLogComment {
            id: None,
            validation_log_id: None,
            user_id: None,
            comment: None,
            created_at: None,
            updated_at: None,
        }
    }
}

