/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationLogCommentsStoreRequest {
    /// ID of the associated validation log
    #[serde(rename = "validation_log_id")]
    pub validation_log_id: i32,
    /// Comment text
    #[serde(rename = "comment")]
    pub comment: String,
}

impl ValidationLogCommentsStoreRequest {
    pub fn new(validation_log_id: i32, comment: String) -> ValidationLogCommentsStoreRequest {
        ValidationLogCommentsStoreRequest {
            validation_log_id,
            comment,
        }
    }
}

