/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationLogCommentsUpdateRequest {
    /// Updated comment text
    #[serde(rename = "comment")]
    pub comment: String,
}

impl ValidationLogCommentsUpdateRequest {
    pub fn new(comment: String) -> ValidationLogCommentsUpdateRequest {
        ValidationLogCommentsUpdateRequest {
            comment,
        }
    }
}

