/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidationLogsUpdateRequest {
    /// Mark the validation log as complete
    #[serde(rename = "complete", skip_serializing_if = "Option::is_none")]
    pub complete: Option<bool>,
    /// Mark the validation log as incomplete
    #[serde(rename = "incomplete", skip_serializing_if = "Option::is_none")]
    pub incomplete: Option<bool>,
    /// Mark the validation log as passed
    #[serde(rename = "pass", skip_serializing_if = "Option::is_none")]
    pub pass: Option<bool>,
    /// Mark the validation log as failed
    #[serde(rename = "fail", skip_serializing_if = "Option::is_none")]
    pub fail: Option<bool>,
    /// Mark the validation log as enabled
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    /// Mark the validation log as disabled
    #[serde(rename = "disable", skip_serializing_if = "Option::is_none")]
    pub disable: Option<bool>,
}

impl ValidationLogsUpdateRequest {
    pub fn new() -> ValidationLogsUpdateRequest {
        ValidationLogsUpdateRequest {
            complete: None,
            incomplete: None,
            pass: None,
            fail: None,
            enable: None,
            disable: None,
        }
    }
}

