/*
 * Safe People Registry API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhooksUpdateReceiverRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "webhook_event_id", skip_serializing_if = "Option::is_none")]
    pub webhook_event_id: Option<i32>,
}

impl WebhooksUpdateReceiverRequest {
    pub fn new() -> WebhooksUpdateReceiverRequest {
        WebhooksUpdateReceiverRequest {
            id: None,
            url: None,
            webhook_event_id: None,
        }
    }
}

